/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POO;

/**
 *
 * @author HECTOR MAURICIO
 */
public class frmRegistro extends javax.swing.JFrame {

    //Intsnacia para asociar a la ventana de ingreso
    private frmIngreso ingreso;
    
    //Intsancia de la clase cientifico 
    private Cientifico cientifico;
    
    String canales;
    String canal1;
    String canal2;
    String canal3;
    String canal4;
    
    
    
    public frmRegistro(String usr, frmIngreso ing) {
        initComponents();
        ingreso = ing; //Asociamos instancia con parametros 
        jtfNombre.setText(usr); //Asociamos el nombre del usuario con el jtfNombre del registro
        cientifico = new Cientifico();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbnRegresar = new javax.swing.JButton();
        jbnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfHorario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbnMostrar = new javax.swing.JButton();
        jcbCientifico = new javax.swing.JCheckBox();
        jcbReportaje = new javax.swing.JCheckBox();
        jcbDocumental = new javax.swing.JCheckBox();
        jrbGeographic = new javax.swing.JRadioButton();
        jrbDiscovery = new javax.swing.JRadioButton();
        jrbRT = new javax.swing.JRadioButton();
        jbnRegistrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcbArticulo = new javax.swing.JCheckBox();
        jrbCosmos = new javax.swing.JRadioButton();
        jcbNacional = new javax.swing.JCheckBox();
        jcbInternacional = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaComentarios = new javax.swing.JTextArea();
        jlbRegistrado = new javax.swing.JLabel();
        jcbPrivado = new javax.swing.JCheckBox();
        jcbPublico = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbnRegresar.setText("Regresar");
        jbnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRegresarActionPerformed(evt);
            }
        });

        jbnLimpiar.setText("Limpiar");
        jbnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Canal");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Horario");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tipo");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Ingrese la Informacion");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre ");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Interes");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Estelar");

        jbnMostrar.setText("Mostrar");
        jbnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnMostrarActionPerformed(evt);
            }
        });

        jcbCientifico.setText("Cientificos");
        jcbCientifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCientificoActionPerformed(evt);
            }
        });

        jcbReportaje.setText("Reportajes");
        jcbReportaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbReportajeActionPerformed(evt);
            }
        });

        jcbDocumental.setText("Documentales");
        jcbDocumental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDocumentalActionPerformed(evt);
            }
        });

        jrbGeographic.setText("National Geographic");
        jrbGeographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGeographicActionPerformed(evt);
            }
        });

        jrbDiscovery.setText("Discovery Channel");
        jrbDiscovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDiscoveryActionPerformed(evt);
            }
        });

        jrbRT.setText("RT");
        jrbRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRTActionPerformed(evt);
            }
        });

        jbnRegistrar.setText("Registrar");
        jbnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRegistrarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Comentarios");

        jcbArticulo.setText("Articulos");
        jcbArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbArticuloActionPerformed(evt);
            }
        });

        jrbCosmos.setText("Cosmos");
        jrbCosmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCosmosActionPerformed(evt);
            }
        });

        jcbNacional.setText("Nacional");
        jcbNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNacionalActionPerformed(evt);
            }
        });

        jcbInternacional.setText("Internacional");
        jcbInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbInternacionalActionPerformed(evt);
            }
        });

        jtaComentarios.setColumns(20);
        jtaComentarios.setRows(5);
        jScrollPane1.setViewportView(jtaComentarios);

        jlbRegistrado.setText("Contenido Registrado");

        jcbPrivado.setText("Privado");
        jcbPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPrivadoActionPerformed(evt);
            }
        });

        jcbPublico.setText("Publico");
        jcbPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPublicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(159, 159, 159)
                        .addComponent(jcbPrivado)
                        .addGap(156, 156, 156)
                        .addComponent(jcbPublico)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(42, 42, 42))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(45, 45, 45))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel2))
                                                    .addGap(35, 35, 35)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                                .addComponent(jtfHorario)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(32, 32, 32)
                                                    .addComponent(jcbNacional)
                                                    .addGap(76, 76, 76)
                                                    .addComponent(jcbInternacional))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(37, 37, 37)
                                            .addComponent(jrbGeographic)
                                            .addGap(26, 26, 26)
                                            .addComponent(jrbDiscovery)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jbnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jrbRT, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(28, 28, 28)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(190, 190, 190)
                                                .addComponent(jbnMostrar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(jcbCientifico)
                                                .addGap(62, 62, 62)
                                                .addComponent(jcbReportaje)))
                                        .addGap(53, 53, 53)
                                        .addComponent(jcbDocumental)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jcbArticulo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jrbCosmos))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jbnRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbnLimpiar)))
                        .addContainerGap(37, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlbRegistrado)
                        .addGap(312, 312, 312))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbNacional)
                    .addComponent(jcbInternacional))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbCientifico)
                    .addComponent(jcbReportaje)
                    .addComponent(jcbDocumental)
                    .addComponent(jcbArticulo))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jrbGeographic)
                    .addComponent(jrbDiscovery)
                    .addComponent(jrbRT)
                    .addComponent(jrbCosmos))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbPublico)
                    .addComponent(jcbPrivado))
                .addGap(29, 29, 29)
                .addComponent(jlbRegistrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnRegistrar)
                    .addComponent(jbnMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnLimpiar)
                    .addComponent(jbnRegresar))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRegresarActionPerformed
        frmIngreso regresar = new frmIngreso(); //Mostrar la ventana de ingreso
        regresar.setVisible(true);
        this.dispose(); //Liberar memoria y eliminar objeto actual
    }//GEN-LAST:event_jbnRegresarActionPerformed

    private void jbnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jbnLimpiarActionPerformed

    private void jbnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnMostrarActionPerformed
        
        //Llamamos la ventana de mostrar y pasamos la infotmacion del objeto
        frmMostrar abrir = new frmMostrar(cientifico , this);
        abrir.setVisible(true); //Muestra la ventana de Registro
        this.setVisible(false);//Hace invisible la ventana actual
       
       
    }//GEN-LAST:event_jbnMostrarActionPerformed

    private void jcbReportajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbReportajeActionPerformed
        // TODO add your handling code here:
              if(jcbReportaje.isSelected())
        {
            jcbDocumental.setSelected(false);
            jcbCientifico.setSelected(false);
            jcbArticulo.setSelected(false);
        }
    }//GEN-LAST:event_jcbReportajeActionPerformed

    private void jbnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRegistrarActionPerformed
        //Evaluar la seleccion de un jRadioButton
       /*
        if(jrbGeographic.isSelected())
        {
            cientifico.setCanal("National Geographic");
        }
        else if(jrbDiscovery.isSelected())
        {
            cientifico.setCanal("National Geographic");
        }
        else if(jrbRT.isSelected())
        {
             cientifico.setCanal("RT");
        }
        else if(jrbCosmos.isSelected())
        {
             cientifico.setCanal("RT");
        }
        else jlbRegistrado.setText("No ha seleccionado ningun canal");*/
        
        if(!jrbGeographic.isSelected()&& jrbDiscovery.isSelected() && jrbRT.isSelected()
                && jrbCosmos.isSelected())
        {
            jlbRegistrado.setText("No se ha seleccionado algun canal");
        }
        
        //Evaluar la seleccion de un jCheckBox
        if(jcbNacional.isSelected())
        {
            cientifico.setEstelar("Nacional");
        }
        else if(jcbInternacional.isSelected())
        {
            cientifico.setEstelar("Internacional");
        }
        if(!jcbNacional.isSelected() && !jcbInternacional.isSelected())
        {
            jlbRegistrado.setText("Ningun Estelar seleccionado");
        }
        
        //Tipo
        if(jcbCientifico.isSelected())
        {
            cientifico.setTipo("Cientifico");
        }
        else if(jcbReportaje.isSelected())
        {
            cientifico.setTipo("Reportaje");
        }
        else if(jcbDocumental.isSelected())
        {
            cientifico.setTipo("Documentales");
        }
        else if(jcbArticulo.isSelected())
        {
            cientifico.setTipo("Articulos");
        }
        if(!jcbCientifico.isSelected() && jcbReportaje.isSelected() && 
                jcbDocumental.isSelected() && jcbArticulo.isSelected())
        {
             jlbRegistrado.setText(jlbRegistrado.getText()+"Ningun tipo seleccionado");
        }
        
        if(jcbPublico.isSelected())
        {
            cientifico.setInteres("Publico");
        }
        else if(jcbPrivado.isSelected())
        {
            cientifico.setInteres("Privado");         
        }
        if(jcbPublico.isSelected() && jcbPrivado.isSelected())
        {
             jlbRegistrado.setText(jlbRegistrado.getText()+"Ningun interes seleccionado");
        }
        
        //Para las cajas multimedias
        cientifico.setComentarios(jtaComentarios.getText());

        //Para los textos
        cientifico.setHorario(jtfHorario.getText());
        
        //Mensaje informativo para el usuario
        jlbRegistrado.setText("Usuario registrado");
        
        canales = (canal1+canal2+canal3+canal4);
        cientifico.setCanal(canales);
        limpiar();
        
          mensajeDeAlerta("Usuario Registrado" , "Registro" );
        
    }//GEN-LAST:event_jbnRegistrarActionPerformed

    private void jrbGeographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGeographicActionPerformed
        // TODO add your handling code here:
        //Esto es para que se puedan seleccionar varios jrb y los imprima en la ventana de mostrar
        if(jrbGeographic.isSelected())
        {
            canal1 = "\n\tNational Geographic";
        }
    }//GEN-LAST:event_jrbGeographicActionPerformed

    private void jrbDiscoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDiscoveryActionPerformed
        // TODO add your handling code here:
        //Esto es para que se puedan seleccionar varios jrb y los imprima en la ventana de mostrar
        if(jrbDiscovery.isSelected())
        {
            canal2 = "\n\tDiscovery Channel";
        }
    }//GEN-LAST:event_jrbDiscoveryActionPerformed

    private void jrbRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRTActionPerformed
        //Esto es para que se puedan seleccionar varios jrb y los imprima en la ventana de mostrar
        if(jrbRT.isSelected())
        {
            canal3 = "\n\t RT";
        }
    }//GEN-LAST:event_jrbRTActionPerformed

    private void jrbCosmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCosmosActionPerformed
        // TODO add your handling code here:
        if(jrbCosmos.isSelected())
        {
            canal4 = "\n\t Cosmos";
        }
    }//GEN-LAST:event_jrbCosmosActionPerformed

    private void jcbInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbInternacionalActionPerformed
        // TODO add your handling code here:
        //Esto es para que solo seleccione una opcion y no pueda las demas
        if(jcbInternacional.isSelected())
        {
            jcbNacional.setSelected(false);
        }
    }//GEN-LAST:event_jcbInternacionalActionPerformed

    private void jcbNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNacionalActionPerformed
        // TODO add your handling code here:
        //Esto es para que solo seleccione una opcion y no pueda las demas
           if(jcbNacional.isSelected())
        {
            jcbInternacional.setSelected(false);
        }
    }//GEN-LAST:event_jcbNacionalActionPerformed

    private void jcbPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPrivadoActionPerformed
        // TODO add your handling code here:
        if(jcbPrivado.isSelected())
        {
            jcbPublico.setSelected(false);
        }
        
    }//GEN-LAST:event_jcbPrivadoActionPerformed

    private void jcbPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPublicoActionPerformed
        if(jcbPublico.isSelected())
        {
            jcbPrivado.setSelected(false);
        }
    }//GEN-LAST:event_jcbPublicoActionPerformed

    private void jcbCientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCientificoActionPerformed
        // TODO add your handling code here:
        //Esto es para que solo seleccione una opcion y no pueda las demas
        if(jcbCientifico.isSelected())
        {
            jcbDocumental.setSelected(false);
            jcbReportaje.setSelected(false);
            jcbArticulo.setSelected(false);
        }
    }//GEN-LAST:event_jcbCientificoActionPerformed

    private void jcbDocumentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDocumentalActionPerformed
        // TODO add your handling code here:
        //Esto es para que solo seleccione una opcion y no pueda las demas
        if(jcbDocumental.isSelected())
        {
            jcbCientifico.setSelected(false);
            jcbReportaje.setSelected(false);
            jcbArticulo.setSelected(false);
        }
    }//GEN-LAST:event_jcbDocumentalActionPerformed

    private void jcbArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbArticuloActionPerformed
        // TODO add your handling code here:
        //Esto es para que solo seleccione una opcion y no pueda las demas
        if(jcbArticulo.isSelected())
        {
            jcbDocumental.setSelected(false);
            jcbReportaje.setSelected(false);
            jcbCientifico.setSelected(false);
        }
    }//GEN-LAST:event_jcbArticuloActionPerformed

     public static void mensajeDeAlerta(String mensaje, String titulo)
    {
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, titulo, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new frmRegistro(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnLimpiar;
    private javax.swing.JButton jbnMostrar;
    private javax.swing.JButton jbnRegistrar;
    private javax.swing.JButton jbnRegresar;
    private javax.swing.JCheckBox jcbArticulo;
    private javax.swing.JCheckBox jcbCientifico;
    private javax.swing.JCheckBox jcbDocumental;
    private javax.swing.JCheckBox jcbInternacional;
    private javax.swing.JCheckBox jcbNacional;
    private javax.swing.JCheckBox jcbPrivado;
    private javax.swing.JCheckBox jcbPublico;
    private javax.swing.JCheckBox jcbReportaje;
    private javax.swing.JLabel jlbRegistrado;
    private javax.swing.JRadioButton jrbCosmos;
    private javax.swing.JRadioButton jrbDiscovery;
    private javax.swing.JRadioButton jrbGeographic;
    private javax.swing.JRadioButton jrbRT;
    private javax.swing.JTextArea jtaComentarios;
    private javax.swing.JTextField jtfHorario;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        //Limpiar cuadros de texto
        jtfNombre.setText("");
        jtfHorario.setText("");
        //Limpiar botones de opcion 
        
        //Limpiar campos de opcion 
        jrbCosmos.setSelected(false);
        jrbDiscovery.setSelected(false);
        jrbGeographic.setSelected(false);
        jrbRT.setSelected(false);
        
        //Limpiar casillas de verificacion 
        jcbInternacional.setSelected(false);
        jcbNacional.setSelected(false);
        
        //Limpiar caja multimedia
        jtaComentarios.setText("");
        
        jcbCientifico.setSelected(false);
        jcbReportaje.setSelected(false);
        jcbDocumental.setSelected(false);
        jcbArticulo.setSelected(false);
        
        jcbPrivado.setSelected(false);
        jcbPublico.setSelected(false);
        
        //Poner el foco de control en la casilla de nombre
        jtfNombre.requestFocus();
      
    
    }
}
